// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjLFb-X0P17-YY5GkHRXTqBZ2fvO9LRN8',
    appId: '1:553206109712:web:9fe3264ab546d69baddc95',
    messagingSenderId: '553206109712',
    projectId: 'my-first-ecommerce-app-b270a',
    authDomain: 'my-first-ecommerce-app-b270a.firebaseapp.com',
    storageBucket: 'my-first-ecommerce-app-b270a.appspot.com',
    measurementId: 'G-7DEC5BJYMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF52vHgqzwVfv-8XjUvjk_xdQiu_svUhI',
    appId: '1:553206109712:android:9cc27fd100a6a6e5addc95',
    messagingSenderId: '553206109712',
    projectId: 'my-first-ecommerce-app-b270a',
    storageBucket: 'my-first-ecommerce-app-b270a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHrsDk4Vqh_jEJdWFHQHQVNNE6W_AQuys',
    appId: '1:553206109712:ios:71582de52b798c9aaddc95',
    messagingSenderId: '553206109712',
    projectId: 'my-first-ecommerce-app-b270a',
    storageBucket: 'my-first-ecommerce-app-b270a.appspot.com',
    iosClientId: '553206109712-tj1en5qrpp1alu0qvtph0sr84153455o.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFlutterApplication',
  );
}
